In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
#this model is  inspired from 
#https://towardsdatascience.com/multi-class-text-classification-with-lstm-1590bee1bd17

In [0]:

##NOT FOR SYSTEMS
!unzip -P ****** -qq '/content/drive/My Drive/EnglishData/task_c_distant.zip' 

In [0]:

import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
import numpy as np

In [0]:

def convertToFloat(val):
    if not val:
        return 0    
    try:
        return np.float64(val)
    except:        
        return np.float64(0)


headers=['id','text','average_ind','average_grp','average_oth','std_ind','std_grp','std_oth']
taskc = pd.read_csv("task_c_distant_ann.tsv", delimiter='\t',names=headers,low_memory=False,converters={"average_ind":convertToFloat,
                                                                                                    "average_grp":convertToFloat,
                                                                                                    "average_oth":convertToFloat,
                                                                                                    "std_ind":convertToFloat,
                                                                                                    "std_grp":convertToFloat,
                                                                                                    "std_oth":convertToFloat})
taskc=taskc[1:]

In [10]:
taskc.head()

id  ...   std_oth
1  1159533712079503361  ...  0.138649
2  1159533713044234241  ...  0.083230
3  1159533718345830400  ...  0.254621
4  1159533739871002625  ...  0.067552
5  1159533742366633984  ...  0.104436

[5 rows x 8 columns]

In [11]:
taskc.values

array([['1159533712079503361',
        '@USER Trump is a fucking idiot his dementia is getting worse',
        0.8334315660070198, ..., 0.20833409336419706,
        0.09893746284301566, 0.1386493230104102],
       ['1159533713044234241',
        '@USER HELL YES! His grinned and thumbs up are disgusting!',
        0.48106237178573397, ..., 0.3452248610539589,
        0.33592350092689993, 0.08323036242339713],
       ['1159533718345830400',
        "@USER Can't wait to see the shit show his death will bring.",
        0.4388127663192773, ..., 0.18260870386171185,
        0.18688048564468512, 0.25462109958562573],
       ...,
       ['1187636295306268673',
        'I meant tool but the point is women ain’t shit. 🙅🏻\u200d♂️🤷🏻\u200d♂️',
        0.36375786996300313, ..., 0.23943555651707127,
        0.16535075005267147, 0.09506541000311416],
       ['1187636299785744384', '@USER i sang too the fuck-',
        0.5982300263631064, ..., 0.19187065632830977,
        0.10707485138459394, 0.115205

In [0]:

dfnumpy=taskc.to_numpy();
x_train=dfnumpy[:, 1].reshape(-1, 1)
y_train1=dfnumpy[:, 2].reshape(-1, 1)
y_train2=dfnumpy[:, 3].reshape(-1, 1)
y_train3=dfnumpy[:, 4].reshape(-1, 1)



In [0]:
y=np.stack((y_train1.flatten(),y_train2.flatten(),y_train3.flatten()), axis=-1, out=None)

In [31]:
y_train2

array([[0.07610979866070268],
       [0.3673629474131143],
       [0.2685740368872388],
       ...,
       [0.43151670865663655],
       [0.16155983352929942],
       [0.15227155079903518]], dtype=object)

In [30]:
y[0:5]

array([[0.8334315660070198, 0.07610979866070268, 0.10776452321727449],
       [0.48106237178573397, 0.3673629474131143, 0.13884137991817902],
       [0.4388127663192773, 0.2685740368872388, 0.3775726696311655],
       [0.7129954339515537, 0.12350408671699416, 0.11113008071093726],
       [0.6914140593727042, 0.14672323837904971, 0.19228166422122278]],
      dtype=object)

In [32]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [0]:
from nltk.tokenize import TweetTokenizer
from nltk.corpus import stopwords 
import re
import string
tknzr = TweetTokenizer(strip_handles=True, reduce_len=True)
stopwords=set(stopwords.words('english'))
def preprocessinglib(arrt):
    ans =[]
    for txt in arrt:
        unique_words = dict.fromkeys(txt.split())
        txt2=' '.join(unique_words)
        tokens=tknzr.tokenize(txt2)
        ctokens=[]
        for t in tokens:
          if  t not in stopwords and t not in string.punctuation :
            ctokens.append(t)
        clean_s = ' '.join(ctokens)
        ans.append(clean_s)
               
    return ans


In [17]:
#encoded_Y

array([1, 0, 1])

In [15]:
dummy_y

array([[0., 1.],
       [1., 0.],
       [0., 1.]], dtype=float32)