In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
#this model is  inspired from 
#https://machinelearningmastery.com/multi-class-classification-tutorial-keras-deep-learning-library/

In [0]:
#https://towardsdatascience.com/multi-class-text-classification-with-lstm-1590bee1bd17

Keras bert inspired from 
https://github.com/strongio/keras-bert

In [0]:

##NOT FOR SYSTEMS
!unzip -P ****** -qq '/content/drive/My Drive/EnglishData/task_c_distant.zip' 

In [0]:

import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from keras.callbacks import EarlyStopping
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
import numpy as np

Using TensorFlow backend.


In [0]:

def convertToFloat(val):
    if not val:
        return 0    
    try:
        return np.float64(val)
    except:        
        return np.float64(0)


headers=['id','text','average_ind','average_grp','average_oth','std_ind','std_grp','std_oth']
taskc = pd.read_csv("task_c_distant_ann.tsv", delimiter='\t',names=headers,low_memory=False,converters={"average_ind":convertToFloat,
                                                                                                    "average_grp":convertToFloat,
                                                                                                    "average_oth":convertToFloat,
                                                                                                    "std_ind":convertToFloat,
                                                                                                    "std_grp":convertToFloat,
                                                                                                    "std_oth":convertToFloat})
taskc=taskc[1:]

In [0]:
taskc.head()

id  ...   std_oth
1  1159533712079503361  ...  0.138649
2  1159533713044234241  ...  0.083230
3  1159533718345830400  ...  0.254621
4  1159533739871002625  ...  0.067552
5  1159533742366633984  ...  0.104436

[5 rows x 8 columns]

In [0]:

dfnumpy=taskc.to_numpy();
x=dfnumpy[:, 1].reshape(-1, 1)
y_train1=dfnumpy[:, 2].reshape(-1, 1)
y_train2=dfnumpy[:, 3].reshape(-1, 1)
y_train3=dfnumpy[:, 4].reshape(-1, 1)
y_std1=dfnumpy[:, 5].reshape(-1, 1)
y_std2=dfnumpy[:, 6].reshape(-1, 1)
y_std3=dfnumpy[:, 7].reshape(-1, 1)

#y_t1=getNewLabel(y_train1,y_std1)
#y_t2=getNewLabel(y_train2,y_std2)
#y_t3=getNewLabel(y_train3,y_std3)


In [0]:
y=np.stack((y_train1.flatten(),y_train2.flatten(),y_train3.flatten()), axis=-1, out=None)

In [0]:
y_train2

array([[0.07610979866070268],
       [0.3673629474131143],
       [0.2685740368872388],
       ...,
       [0.43151670865663655],
       [0.16155983352929942],
       [0.15227155079903518]], dtype=object)

In [0]:
y[0:5]

array([[0.8334315660070198, 0.07610979866070268, 0.10776452321727449],
       [0.48106237178573397, 0.3673629474131143, 0.13884137991817902],
       [0.4388127663192773, 0.2685740368872388, 0.3775726696311655],
       [0.7129954339515537, 0.12350408671699416, 0.11113008071093726],
       [0.6914140593727042, 0.14672323837904971, 0.19228166422122278]],
      dtype=object)

In [0]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [0]:
from nltk.tokenize import TweetTokenizer
from nltk.corpus import stopwords 
import re
import string
tknzr = TweetTokenizer(strip_handles=True, reduce_len=True)
stopwords=set(stopwords.words('english'))
def preprocessinglib(arrt):
    ans =[]
    for txt in arrt:
        unique_words = dict.fromkeys(txt.split())
        txt2=' '.join(unique_words)
        tokens=tknzr.tokenize(txt2)
        ctokens=[]
        for t in tokens:
          if  t not in stopwords and t not in string.punctuation :
            ctokens.append(t.lower())
        clean_s = ' '.join(ctokens)
        ans.append(clean_s)
               
    return ans


In [0]:
preprocessedTweets=preprocessinglib(x[:,0])

In [0]:
from sklearn.utils import shuffle
preprocessedTweets,y=shuffle(preprocessedTweets,y)

In [0]:
preprocessedTweets

["you're full shit know i seething foam-mouthed women probably men",
 'send flushed emojis bro fuck eat ass club penguin rewritten',
 'imagine stealing content smaller youtuber ... fuck community',
 'screaming bc im literally making fantasy tweet fuck wrong oh god',
 '“ she friend ” bitch i showed dick',
 'then i went check pics ’ worth none shit talking 😩 😩 😩',
 'im going thru miss jaehyun fuck',
 'who tf trying hack bitch ’ even followers go back',
 "im reading one lady's tweets train ran food hour ago holy shit",
 'currently 3 crying ’ high fuck',
 '’ nothing worse lying i hate shit',
 'fuck gamers fuck gaming',
 'not directed ’ respected ‼ ️ ‼ ️ ‼ ️ 🤣 shut shit 🤣 🤣 🤣',
 'i hate getting work bitch diversity',
 'an absolute gentleman greg ... fair fucking play 🙌 🏻 🙌 🏻 #loveislandfinal',
 'stupid hell i get tired parents posting trash videos called disciplining kids',
 'what disgusting attempt cover behavior',
 'and niggas wanna laugh joke ’ going process damn shame',
 'men beat yo as

In [0]:
# Import the dependencies
from keras.models import Sequential
from keras.layers import Dense, LSTM,SpatialDropout1D
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence

In [0]:
# The maximum number of words to be used. (most frequent)
MAX_NB_WORDS = 60000
# Max number of words in each complaint.
MAX_SEQUENCE_LENGTH = 512
# This is fixed.
EMBEDDING_DIM = 128

In [0]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

In [0]:
tokenizer = Tokenizer(num_words=MAX_NB_WORDS, filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~', lower=True)
tokenizer.fit_on_texts(preprocessedTweets)
word_index = tokenizer.word_index
print('Found %s unique tokens.' % len(word_index))


Found 60150 unique tokens.


In [0]:
X = tokenizer.texts_to_sequences(preprocessedTweets)
X = pad_sequences(X, maxlen=MAX_SEQUENCE_LENGTH)
print('Shape of data tensor:', X.shape)

Shape of data tensor: (188973, 512)


In [0]:
y.shape

(188973, 3)

In [0]:
x_train=X
y_train=y

In [0]:

#GET THE DATA FROM THE PANDAS FRAME
headers=['id','tweet','subtask_a','subtask_b','subtask_c']
englishdata = pd.read_csv("/content/drive/My Drive/EnglishData/OLIDv1.0/olid-training-v1.0.tsv", delimiter='\t',names=headers,low_memory=False)
englishdata=englishdata[['id','tweet','subtask_c']]
englishdata=englishdata[1:]

In [0]:
englishdata = englishdata.dropna(subset=['subtask_c'])

In [0]:
englishdata.head()

id                                              tweet subtask_c
2   90194  @USER @USER Go home you’re drunk!!! @USER #MAG...       IND
6   97670                  @USER Liberals are all Kookoo !!!       OTH
8   52415  @USER was literally just talking about this lo...       GRP
10  13384  @USER Canada doesn’t need another CUCK! We alr...       IND
13  28414  @USER you are a lying corrupt traitor!!! Nobod...       IND

In [0]:
import tensorflow as tf

In [0]:
dfnumpy=englishdata.to_numpy()
x_test=dfnumpy[:, 1].reshape(-1, 1)
y_test=dfnumpy[:, 2].reshape(-1, 1)

In [0]:
y_test

array([['IND'],
       ['OTH'],
       ['GRP'],
       ...,
       ['GRP'],
       ['IND'],
       ['OTH']], dtype=object)

In [0]:
y_test.flatten()

array(['IND', 'OTH', 'GRP', ..., 'GRP', 'IND', 'OTH'], dtype=object)

In [0]:
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

def f1_calc(predictions,labels):
  #rowwise return the index of the max element ie 0 or 1 depending on the maximum value returned
  predictionArgmax=np.argmax(predictions,axis=1).to('cpu').numpy().flatten()
  labelsFlattend=np.argmax(predictions,axis=1).to('cpu').numpy().flatten()
  print(predictions)
  print("Predictions Argmax",predictionArgmax)
  print("labels Flattened",labelsFlattend)   
  return f1_score(labelsFlattend, predictionArgmax, average='macro')

In [0]:
len(y_test)

3876

In [0]:
#f1 inspired from 
#https://datascience.stackexchange.com/questions/45165/how-to-get-accuracy-f1-precision-and-recall-for-a-keras-model

In [41]:
model = Sequential()
model.add(Embedding(MAX_NB_WORDS, EMBEDDING_DIM, input_length=x_train.shape[1]))
model.add(SpatialDropout1D(0.2))
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

epochs = 3
batch_size = 64

history = model.fit(x_train, y_train, epochs=epochs, batch_size=batch_size,validation_split=0.1,callbacks=[EarlyStopping(monitor='val_loss', patience=3, min_delta=0.0001)])

Train on 170075 samples, validate on 18898 samples
Epoch 1/3
170075/170075 [==============================] - 3521s 21ms/step - loss: 1.0363 - acc: 0.8656 - val_loss: 1.0306 - val_acc: 0.8723
Epoch 2/3
170075/170075 [==============================] - 3524s 21ms/step - loss: 1.0277 - acc: 0.8806 - val_loss: 1.0298 - val_acc: 0.8746
Epoch 3/3
170075/170075 [==============================] - 3522s 21ms/step - loss: 1.0248 - acc: 0.8887 - val_loss: 1.0302 - val_acc: 0.8742


In [0]:

# serialize model to JSON
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("/content/drive/My Drive/EnglishData/SubtaskCEnglishDatafinalepoch3512.h5")

In [43]:
x_test

array([['@USER @USER Go home you’re drunk!!! @USER #MAGA #Trump2020 👊🇺🇸👊 URL'],
       ['@USER Liberals are all Kookoo !!!'],
       ['@USER was literally just talking about this lol all mass shootings like that have been set ups. it’s propaganda used to divide us on major issues like gun control and terrorism'],
       ...,
       ['@USER @USER @USER @USER Liars like the Antifa twins you vigorously defend?'],
       ['@USER Sometimes I get strong vibes from people and this man’s vibe is tens of millions of murders - he is more dangerous than DT.'],
       ["@USER And why report this garbage.  We don't give a crap."]],
      dtype=object)

In [0]:
preprocessedTweets1=preprocessinglib(x_test[:,0])

In [45]:
X_1 = tokenizer.texts_to_sequences(preprocessedTweets1)
X_test = pad_sequences(X_1, maxlen=MAX_SEQUENCE_LENGTH)
print('Shape of data tensor:', X_test.shape)

Shape of data tensor: (3876, 512)


In [0]:
def giveLabel2(y1):
  i=0
  largest_index=0
  #label1=['IND','GRP','OTH']
  ylabels=[]
  for r in y1:
    if (r=="IND"): 
        largest_index = 0 
    elif (r=="GRP"):
        largest_index = 1 
    else: 
        largest_index = 2 
    
    ylabels.append(largest_index)
    i=i+1;
  return ylabels

In [0]:
yz=giveLabel2(y_test)

In [48]:
set(yz)

{0, 1, 2}

In [0]:
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(yz)
encoded_Y = encoder.transform(yz)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)

In [50]:
dummy_y

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]], dtype=float32)

In [51]:
pip install h5py

In [52]:
encoder.classes_

array([0, 1, 2])

In [0]:

# serialize model to JSON
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("SubtaskCEnglishDatafinalepoch3512.h5")

In [0]:
from keras.models import model_from_json


In [0]:
# load json and create model
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("SubtaskCEnglishDatafinalepoch3512.h5")
print("Loaded model from disk")

In [53]:
score= model.evaluate(X_test,dummy_y)
print('Test set\n  Loss: {:0.3f}\n  Accuracy: {:0.3f}'.format(score[0],score[1]))

3876/3876 [==============================] - 18s 5ms/step
Test set
  Loss: 0.749
  Accuracy: 0.746


In [0]:
yvalid=model.predict_classes(X_test)

In [56]:
type(X_test)

numpy.ndarray

In [0]:
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

def calculateF1Score(predictions,labels):
  #rowwise return the index of the max element ie 0 or 1 depending on the maximum value returned
  predictionArgmax=predictions.flatten()
  labelsFlattend=labels.flatten()
  #print("Predictions Argmax",predictionArgmax)
  #print("labels Flattened",labelsFlattend)   
  return f1_score(labelsFlattend, predictionArgmax, average='macro'),accuracy_score(labelsFlattend, predictionArgmax)



In [0]:
f11,acc=calculateF1Score(yvalid,encoded_Y)

In [59]:
acc

0.7458720330237358

In [60]:
f11

0.6140274585740214

In [0]:
ygiven=[]
ypredicted=[]

In [0]:
!unzip -P ****** -qq '/content/drive/My Drive/EnglishData/test_c_baseline.csv.zip' 

In [0]:
!unzip -P ****** -qq '/content/drive/My Drive/EnglishData/public_data_task_C.zip'

In [0]:
def readData1():
  headers=['id','ypredicted']
  greekdataBaseline = pd.read_csv("test_c_baseline.csv", delimiter=',',names=headers)
  #,converters={"id":convertToInt}       
  #greekdataBaseline.id = greekdataBaseline.id.astype(int)
  #greekdataBaseline=greekdataBaseline[1:]
  print(greekdataBaseline.head())
  print(greekdataBaseline.shape)

  headers=['id','tweet']
  greekDataTest = pd.read_csv("test_c_tweets.tsv", delimiter='\t',names=headers)
                                #converters={"id":convertToInt})
  #greekDataTest=greekDataTest[1:]
  print(greekDataTest.head())
  #print(greekDataTest.dtypes)
  print(greekDataTest.shape)
  result = pd.merge(greekDataTest, greekdataBaseline, on='id', how='inner')
  print(result.head())
  print(result.dtypes)
  print(result.shape)

  #result=
  #result.sort_values(by=['id'], inplace=True)
  #print(result.head())
  dfnumpy=result.to_numpy();
  X=dfnumpy[:, 1].reshape(-1, 1)
  y=dfnumpy[:, 2].reshape(-1, 1)
  tid=dfnumpy[:, 0].reshape(-1, 1)
  preprocessedTweets=X[:,0]
  return preprocessedTweets,y,tid

In [66]:
preprocessedTweets,ypredict1,tid=readData1()

     id ypredicted
0   BC0        IND
1   BC3        IND
2   BC9        IND
3  BC10        IND
4  BC19        IND
(850, 2)
     id                                              tweet
0    id                                              tweet
1   BC0  @USER Lmao bihhh dis what u do to your homies ...
2   BC3  @USER The POTUS is a racist, racist, racist, r...
3   BC9  @USER He then grinned, raising his brow.  Oh d...
4  BC10         Niggas priorities be fucked all the way up
(851, 2)
     id                                              tweet ypredicted
0   BC0  @USER Lmao bihhh dis what u do to your homies ...        IND
1   BC3  @USER The POTUS is a racist, racist, racist, r...        IND
2   BC9  @USER He then grinned, raising his brow.  Oh d...        IND
3  BC10         Niggas priorities be fucked all the way up        IND
4  BC19  You bitches really be walking around talking s...        IND
id            object
tweet         object
ypredicted    object
dtype: object
(850, 3)


In [67]:
type(preprocessedTweets)

numpy.ndarray

In [0]:
preprocessedTweets=preprocessinglib(preprocessedTweets)

In [69]:
Xpredict = tokenizer.texts_to_sequences(preprocessedTweets)
Xpredict = pad_sequences(Xpredict, maxlen=MAX_SEQUENCE_LENGTH)
print('Shape of data tensor:', Xpredict.shape)

Shape of data tensor: (850, 512)


In [0]:
ynew = model.predict_classes(Xpredict)

In [0]:
yz=giveLabel2(ypredict1)

In [72]:
set(yz)

{0}

In [0]:
encoded_Ypredict = encoder.transform(yz)


In [0]:
f11,acc=calculateF1Score(ynew,encoded_Ypredict)

In [75]:
f11

0.29188712522045857

In [76]:
acc

0.7788235294117647

In [77]:
print(ynew.flatten().tolist().count(0))
print(ynew.flatten().tolist().count(1))
print(ynew.flatten().tolist().count(2))


662
165
23


In [0]:
yans=ynew.flatten().tolist()

In [0]:
yans3=[]
#yans3.append("IND")

In [0]:
for i in range(len(yans)):
  if yans[i]==0:
    yans3.append("IND")
  elif yans[i]==1:
    yans3.append("GRP")
  else:
    yans3.append("OTH")


In [81]:
tid.shape

(850, 1)

In [0]:
#z={'tweet':sentence_predict[],'subtask_a':y_predict}
#print(len(z))
C = {'id': tid.flatten(),
        'predicted': yans3
    }
df = pd.DataFrame(C)
#print (df[df['id'] == 2707] )

export_csv = df.to_csv ('/content/drive/My Drive/EnglishData/EnglishSubtaskCAnswerFinalOneHot.csv', index = None, header=False)

